spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo_list?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: my-secret-pw

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate :
        format_sql: true
    database: mysql



